---
- block:
  - name: Install base packages
    apt:
      name: software-properties-common

  - name: Add ansible repository
    apt_repository:
      repo: ppa:ansible/ansible

  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install base packages
    apt:
      name: ansible
