---
- block:
  - name: Download docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-linux-x86_64
      dest: /usr/bin/docker-compose
      mode: 0755

  - name: Add bash completion
    get_url:
      url: https://raw.githubusercontent.com/docker/compose/1.21.2/contrib/completion/bash/docker-compose
      dest: /etc/bash_completion.d/docker-compose
