---
- block:
  - include_tasks: ubuntu.yml
    when: ansible_distribution == "Ubuntu"

  - include_tasks: rhel.yml
    when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

  - name: Install docker-py for usage with ansible
    pip:
      name: docker-py
