---
- block:
  - name: Add Docker CE repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker.repo
      mode: 0644
      owner: root
      group: root

  - name: Install Docker CE
    yum:
      name: docker-ce
      state: present

  - name: Add ansible user to docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker

  - name: Add docker configuration directory
    file:
      state: directory
      owner: root
      path: /etc/docker
      group: root
      mode: 0644

  - name: Add the daemon.json config file
    template:
      src: templates/daemon.json.j2
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: 0644

  - name: Enable and start docker service
    service:
      name: docker
      state: started
      enabled: yes
