- block:
  - name: Install base packages
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - epel-release
      - vim
      - htop
      - tmux
      - curl
      - wget
      - gnupg2
      - git
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python2-pip
      - bash-completion
      - iotop
      - nmap
      - tcpdump
      - netstat
