- block:
  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install base packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - vim
      - tmux
      - htop
      - apt-transport-https
      - ca-certificates
      - curl
      - wget
      - software-properties-common
      - gnupg2
      - unzip
      - tar
      - git
      - iotop
      - nmap
      - tcpdump